spring.application.name=demo0002


spring.security.user.name=dd
spring.security.user.password=dd


#logging.level.org.springframework.security=DEBUG


spring.datasource.url=jdbc:postgresql://localhost:5432/demo0001
spring.datasource.username=postgres
spring.datasource.password=fawad
#spring.jpa.properties.hibernate.dialect=org.hibernate
#spring.jpa.show
#spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


